[default]
SQLALCHEMY_DATABASE_URI = 'sqlite:///teste.db'
TITLE = 'Teste'
SECRET_KEY = '12345'

EXTENSIONS = [
    "app.extensions.commands",
    "app.extensions.database",
    "app.extensions.admin",
    "app.extensions.appearance",
    "app.extensions.auth",
    "app.blueprints.views",
    "app.blueprints.restapi",
]

[production]
SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector:/'